//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WolframLanguage.Activities.Design.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WolframLanguage.Activities.Design.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolfram Language.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click to view.
        /// </summary>
        public static string DoubleClickToView {
            get {
                return ResourceManager.GetString("DoubleClickToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Activity Here.
        /// </summary>
        public static string DropActivityHere {
            get {
                return ResourceManager.GetString("DropActivityHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate.
        /// </summary>
        public static string EvaluateScopeCategory {
            get {
                return ResourceManager.GetString("EvaluateScopeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel.
        /// </summary>
        public static string KernelScopeCategory {
            get {
                return ResourceManager.GetString("KernelScopeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Data.
        /// </summary>
        public static string LowLevelGetDataScopeCategory {
            get {
                return ResourceManager.GetString("LowLevelGetDataScopeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet Management.
        /// </summary>
        public static string LowLevelPacketScopeCategory {
            get {
                return ResourceManager.GetString("LowLevelPacketScopeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put Data.
        /// </summary>
        public static string LowLevelPutDataScopeCategory {
            get {
                return ResourceManager.GetString("LowLevelPutDataScopeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Level.
        /// </summary>
        public static string LowLevelScopeCategory {
            get {
                return ResourceManager.GetString("LowLevelScopeCategory", resourceCulture);
            }
        }
    }
}
