//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WolframLanguage.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WolframLanguage.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Evaluate activity that goes inside the scope..
        /// </summary>
        public static string EvaluateActivityDescription {
            get {
                return ResourceManager.GetString("EvaluateActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate Activity.
        /// </summary>
        public static string EvaluateActivityDisplayName {
            get {
                return ResourceManager.GetString("EvaluateActivityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Wolfram Language expression to evaluate..
        /// </summary>
        public static string EvaluateActivityExpressionDescription {
            get {
                return ResourceManager.GetString("EvaluateActivityExpressionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression.
        /// </summary>
        public static string EvaluateActivityExpressionDisplayName {
            get {
                return ResourceManager.GetString("EvaluateActivityExpressionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of the evaluation..
        /// </summary>
        public static string EvaluateActivityResultDescription {
            get {
                return ResourceManager.GetString("EvaluateActivityResultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string EvaluateActivityResultDisplayName {
            get {
                return ResourceManager.GetString("EvaluateActivityResultDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate mathematica expression to a .NET Image object.
        /// </summary>
        public static string EvaluateToImageActivityDescription {
            get {
                return ResourceManager.GetString("EvaluateToImageActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate to Image.
        /// </summary>
        public static string EvaluateToImageActivityDisplayName {
            get {
                return ResourceManager.GetString("EvaluateToImageActivityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The width of the exported .NET Image object.
        /// </summary>
        public static string EvaluateToImageActivityHeightDescription {
            get {
                return ResourceManager.GetString("EvaluateToImageActivityHeightDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Height.
        /// </summary>
        public static string EvaluateToImageActivityHeightDisplayName {
            get {
                return ResourceManager.GetString("EvaluateToImageActivityHeightDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The width of the exported .NET Image object.
        /// </summary>
        public static string EvaluateToImageActivityWidthDescription {
            get {
                return ResourceManager.GetString("EvaluateToImageActivityWidthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Width.
        /// </summary>
        public static string EvaluateToImageActivityWidthDisplayName {
            get {
                return ResourceManager.GetString("EvaluateToImageActivityWidthDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate mathematica expression to an ascii string as it would be typed in the shell..
        /// </summary>
        public static string EvaluateToInputFormActivityDescription {
            get {
                return ResourceManager.GetString("EvaluateToInputFormActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate to Input Form.
        /// </summary>
        public static string EvaluateToInputFormActivityDisplayName {
            get {
                return ResourceManager.GetString("EvaluateToInputFormActivityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate mathematica expression to an ascii string as it would be displayed in the shell..
        /// </summary>
        public static string EvaluateToOutputFormActivityDescription {
            get {
                return ResourceManager.GetString("EvaluateToOutputFormActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate to Output Form.
        /// </summary>
        public static string EvaluateToOutputFormActivityDisplayName {
            get {
                return ResourceManager.GetString("EvaluateToOutputFormActivityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}.
        /// </summary>
        public static string MetadataValidationError {
            get {
                return ResourceManager.GetString("MetadataValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolfram Language Scope.
        /// </summary>
        public static string ParentScope {
            get {
                return ResourceManager.GetString("ParentScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mathematica Kernel Arguments to use when opening kernel..
        /// </summary>
        public static string ParentScopeArgsDescription {
            get {
                return ResourceManager.GetString("ParentScopeArgsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel Arguments.
        /// </summary>
        public static string ParentScopeArgsDisplayName {
            get {
                return ResourceManager.GetString("ParentScopeArgsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scope that opens a connection to a wolfram language kernel..
        /// </summary>
        public static string ParentScopeDescription {
            get {
                return ResourceManager.GetString("ParentScopeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to your MathKernel.exe.
        /// </summary>
        public static string ParentScopePathDescription {
            get {
                return ResourceManager.GetString("ParentScopePathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel Path.
        /// </summary>
        public static string ParentScopePathDisplayName {
            get {
                return ResourceManager.GetString("ParentScopePathDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for client to be ready....
        /// </summary>
        public static string WolframLanguageScope_Execute_Waiting_for_client_to_be_ready___ {
            get {
                return ResourceManager.GetString("WolframLanguageScope_Execute_Waiting_for_client_to_be_ready___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Scope complete..
        /// </summary>
        public static string WolframLanguageScope_OnCompleted_Parent_Scope_complete_ {
            get {
                return ResourceManager.GetString("WolframLanguageScope_OnCompleted_Parent_Scope_complete_", resourceCulture);
            }
        }
    }
}
